### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by cleesmith** [fern4lvarez/go-metainspector#5]
Per instructions:
```
go get -u github.com/fern4lvarez/go-metainspector/metainspector
```
yields:
```
package github.com/fern4lvarez/go-metainspector/metainspector
	imports go.marzhillstudios.com/pkg/go-html-transform/h5: unrecognized import path "go.marzhillstudios.com/pkg/go-html-transform/h5"
```

**Comment by fern4lvarez** [comment]
Apparently the go.marzhillstudios.com/pkg/go-html-transform alias to https://bitbucket.org/zaphar/go-html-transform fails. I'll contact the author. Thanks for reporting!

**Comment by fern4lvarez** [comment]
It should be fixed now. Please retry.

**Comment by cleesmith** [comment]
It is, thanks.

**Comment by bennidhamma** [comment]
I'm still seeing this issue. Has it been fixed?

**Comment by fern4lvarez** [comment]
Looks like the author of `go-html-transform` definitely put down the project. I'll use this mirror: https://github.com/imdario/go-html-transform

Please stay tuned.

**Comment by fern4lvarez** [comment]
@bennidhamma it should be fixed again.
